
name: Building AMI on Merge

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
on:
  push:
    branches: [ main, test ]
    paths:
      - ami-ubuntu.pkr.hcl


jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.3

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Installing packer provisioners
      run: packer init ami-ubuntu.pkr.hcl


    - name: Printing the contents of Directory
      run: ls -la


    - name: Building Packer Template
      run: packer build ami-ubuntu.pkr.hcl

    - name: Printing the contents of Directory after building
      run: ls -la