
name: Building AMI on Merge to Main

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
on:
  push:
    branches: [ assgn-9 ]

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.3

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Installing packer provisioners
      run: packer init ami-ubuntu.pkr.hcl

    - name: Building Packer Template
      run: packer build ami-ubuntu.pkr.hcl 2>&1 | sudo tee output.txt; tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' >> ami.txt
    
    - name: modifying template version
      run: aws ec2 modify-launch-template --launch-template-id lt-0839a8c98b1329148 --default-version 1